Device: core: config: app_tz: fix compilation error
Fix the below compilation error due to missing semicolon,
In file included from ensemble-cmsis-dfp_DEV/Device/core/common/source/system.c:44:
ensemble-cmsis-dfp_DEV/Device/core/common/config/app_tz.h:1153:5: error: expected ';' after expression
    SAU_INIT_REGION(0);
    ^
ensemble-cmsis-dfp_DEV/Device/core/common/config/app_tz.h:1140:5: note: expanded from macro 'SAU_INIT_REGION'
    } while (0)
    ^

Signed-off-by: Sudhir Sreedharan <sudhir@alifsemi.com>